"""Analisa um arquivo de cluster e calcula métricas de avaliação.

Uso: execute o módulo apontando para o JSON do cluster e o JSON com as descrições
do conjunto de avaliação. Exemplo:

python -m baseline.analisador_caso_real
    --cluster json/cluster_teste.json
    --dataset json/descricoes_saude.json

O script contará verdadeiros positivos/negativos, falsos positivos/negativos
com base nas listas `SIMILARES` e `NAO_SIMILARES` definidas abaixo e imprimirá
precision, recall, f1 e accuracy.
"""
from __future__ import annotations

import argparse
import json
import unicodedata
from pathlib import Path
from typing import Iterable


DESCRICOES_SAUDE_PATH = Path(__file__).resolve().parents[1] / "json" / "descricoes_saude.json"

SIMILARES = [
    "COLETOR 20 LITROS PARA MATERIAL PERFUROCORTANTE E BIOLÓGICO DESCARTÁVEL DE PAPELÃO. CAPACIDADE ÚTIL MÍNIMA DE 17 LITROS E MÁXIMA DE 20 LITROS. COM TRAVA ESPECIAL DE SEGURANÇA QUE IMPEÇA A VIOLAÇÃO, PAREDES RÍGIDAS, COM CINTA INTERNA DE SEGURANÇA, BANDEJA E SACO PLÁSTICO RESISTENTE A PERFURAÇÕES E VAZAMENTOS. BOCAL DEVE PERMITIR COLOCAÇÃO DO MATERIAL DESCARTADO UTILIZANDO APENAS UMA DAS MÃOS, DE FORMA SEGURA. ALÇAS PARA TRANSPORTE E TAMPA PROTETORA. SUPERFÍCIE EXTERNA DE COR AMARELA E SÍMBOLO PARA MATERIAL INFECTANTE (NBR 7500)",
    "AQUISIÇÃO DE MATERIAL MÉDICO HOSPITALAR",
    "Material de proteção e segurança",
    "Medicamentos - Drogas e tratamentos médicos para uso humano.\n",
    "Material de Proteção e Segurança - Equipamentos de segurança pessoal e coletiva.\n",
    "AQUISIÇÃO DE INSTRUMENTAL CIRÚRGICO HOSPITALAR",
    "AQUISIÇÃO DE MEDICAMENTOS VETERINÁRIOS",
    "DETERGENTE ENZIMÁTICO- SOLUÇÃO LIMPADORA ENZIMÁTICA CONTENDO 5 ENZIMAS E 2 TENSOATIVOS NÃO IÔNICOS, NÃO CORROSIVO ATÓXICO -CONTENDO PROTEASE, PEPTIDASE, ,LÍPASE, CARBOAHIDRASE, PH NEUTRO BIODEGRADÁVEL, NÃO IRRITANTE A PELE E MUCOSA, APRESENTAR O VALOR EM REAIS DO L DILUÍDO EM SEU MENOR RENDIMENTO DA PREPARAÇÃO ENZIMÁTICA POR GALÃO, ESPECIFICO PARA LIMPEZA DE INSTRUMENTAIS, EQUIPAMENTOS E ARTIGOS MÉDICOS POR MEIOS MANUAIS OU AUTOMATIZADOS, ACONDICIONADO EM FRASCO QUE GARANTA A INTEGRIDADE DO PROD",
    "ESFIGMOMANÔMETRO COM AS CARACTERÍSTICAS MÍNIMAS: APARELHO DE PRESSÃO MECÂNICO ANERÓIDE COM BRAÇADEIRA INCLUSA TAMANHO ADULTO SEM ENGRENAGENS; RESISTENTES A QUEDAS, ATENDE AS NORMAS DA AAMI DE RESISTÊNCIA A IMPACTOS A QUEDA DE ATÉ 76 CM, NÃO QUEBRA E NÃO PERDE A CALIBRAÇÃO DESIGN ERGONÔMICO QUE PERMITE TRABALHAR COM MÃO DIREITA OU ESQUERDA; GARANTIA DE CALIBRAÇÃO POR 5 ANOS; MANÔMETRO ANERÓIDE GIRA 360° PARA FÁCIL VISUALIZAÇÃO E DEVE TER ANEL DE BORRACHA PARA PROTEÇÃO; COM SISTEMA DE TROCA FÁCIL PARA MULTIPLAS BRAÇADEIRAS; COM INDICADOR DE VALORES DA PRESSÃO CONSTITUÍDO POR PONTEIRO QUE SE DESLOCA SOBRE UMA ESCALA CIRCULAR, FORNECENDO A INDICAÇÃO DA PRESSÃO ARTERIAL, ATENDENDO APROXIMADAMENTE A SEGUINTE FAIXA DE ESCALA, FAIXA DE MEDIÇÃO DE MEDIÇÃO: 0 A 300 MMHG; MANGUITO E PERA INSUFLADORA: LIVRES DE LÁTEX. NÃO DEVE DEPENDER DE PILHAS, BATERIAS OU QUALQUER FONTE ELÉTRICA PARA A SUA UTILIZAÇÃO. BRAÇADEIRA QUE ACOMPANHA O MANÔMETRO DEVE SER DO TAMANHO ADULTO; DEVE TER SELO DO INMETRO E LIVRE DE LÁTEX; POSSUI SISTEMA DE TROCA RÁPIDA DE BRAÇADEIRAS; BRAÇADEIRA; CONFECCIONADA EM NYLON, COM FECHAMENTO POR VELCRO DE ALTA DURAÇÃO E LAVÁVEL. DURABILIDADE DE ATÉ 100.000 CICLOS",
    "Medicamentos",
    "Material Hospitalar - Equipamentos e suprimentos médicos para hospitais e clínicas.\n",
    "Mat. e Medicamentos p/uso Veterinário - Produtos usados no tratamento de saúde animal, incluindo medicamentos e instrumentos.\n",
    "Outros materiais médicos hospitalar",
    "MATERIAIS E MEDICAMENTOS PARA USO VETERINÁRIO",
    "Mat. de Coudelaria ou de Uso Zootécnico - Itens usados no cuidado e treinamento de animais, especialmente em ambientes rurais ou zootécnicos.\n",
    "MATERIAL DE PROTEÇÃO E SEGURANÇA",
    "MATERIAL FARMACOLÓGICO",
    "MATERIAL HOSPITALAR",
    "MATERIAL LABORATORIAL",
    "MATERIAL ODONTOLÓGICO",
    "COLETOR PARA MATERIAL PERFUROCORTANTE, LOCAL PARADESCARTE DE AGULHAS, LÂMINAS E OUTROS MATERIAIS CONTAMINADOS PERFURANTES E CORTANTES DESCARTÁVEIS. TOTAL PROTEÇÃO CONTRA PERFURAÇÃO E VAZAMENTO DE FLUIDOS, MAIOR PROTEÇÃO PARA PROFISSIONAIS E PESSOALDE LIMPEZA. COR EXTERNA: AMARELA, COM DIZERES EM PRETO. CAPACIDADE INTERNA: 7 LITROS. APRESENTAÇÃO:CAIXA DE 10 UNIDADES.",
    "OTOSCÓPIO COMPACTO COM ILUMINAÇÃO DE FIBRA ÓTICA E COM TECNOLOGIA XÊNON ,CORPO DE ALTA RESISTÊNCIA A IMPACTOS, DEVE PERMITIR A CONEXÃO COM INSUFLADOR PARA TESTE PNEUMÁTICO DO TÍMPANO, JANELA DE VISÃO COM GIRO PARA OS LADOS. DEVE POSSUIR CABO CONVERSORCOM ENGATE DE SISTEMA TIPO ROSCA, COM BATERIA RECARREGÁVEL E COM REGULAGEM DE INTENSIDADE DE LUZ. ACESSÓRIOS ACOMPANHANTES: JOGO DE ESPÉCULOS REUSÁVEIS (MÍNIMO DE CINCO); UM (01) CARREGADOR; DUAS (02) LÂMPADAS SOBRESSALENTES; ESTOJO PARA ACONDICIONAMENTO. REGISTRO NO MINISTÉRIO DA SAÚDE. GARANTIA MÍNIMA DE 24 MESES; ASSINTÊNCIA TECNICA NA REGIÃO DE SANTA CATARINA, DEVENDO NA PROPOSTA APRESENTAR DECLARAÇÃO DO FABRICANTE OU REPRESENTANTE INDICANDO A EMPRESA RESPONSÁVEL PELOS SERVIÇOS DE ASSISTÊNCIA TÉCNICA. APARELHO DEVE SER BIVOLT OU 220 V.",
    "APARELHO PARA AFERIÇÃO DE PRESSÃO ARTERIAL ADULTOGRANDE (OBESO), COM ESFIGMOMANÔMETRO DO TIPO ANEROIDEDE ALTA SENSIBILIDADE, COM GRADUAÇÃO DE 0 A 300 MMHG, COMCAIXA INJETADA EM LIGA DE ZINCO COM PINTURA DE ALTARESISTÊNCIA, MOSTRADOR PLANO. BRAÇADEIRA EM NYLON ANTI-ALÉRGICO, COM TRATAMENTO IMPERMEÁVEL, LAVÁVEL, COMFECHAMENTO EM VELCRO RESISTENTE, QUE PERMITA OTRAVAMENTO TOTAL E QUE NÃO SOLTE AO INFLAR. VÁLVULA DEMETAL COM REGULAGEM DA SAÍDA DE AR SENSÍVEL, MANGUITO EPERA INSUFLADORA EM PVC ANTI-ALÉRGICO, MANGUITO COMDUAS SAÍDAS, SEM EMENDAS; PERA INSUFLADORA COM SISTEMADE RETORNO EM METAL, COM ESFERA DE AÇO INOX. ACOMPANHABOLSA PARA TRANSPORTE. DEVE APRESENTAR REGISTRO NOMINISTÉRIO DA SAÚDE E GARANTIA DE NO MÍNIMO 1 ANO. (CIM6360)",
    "PAPEL GRAU CIRÚRGICO, BOBINAS LISAS, PERMEÁVEIS AO VAPOR E AO AR, IMPERMEÁVEIS A MICRORGANISMOS, RESISTENTES AO CALOR, LIVRES DE NUTRIENTES MICROBIANOS E RESÍDUOS TÓXICOS, TRANSPARÊNCIA DO FILME. DOTADA DE INDICADORES QUÍMICOS QUE MUDAM DE COR APÓS O PROCESSO DE ESTERILIZAÇÃO. TAMANHO 12CMX100M.",
    "PAPEL GRAU CIRÚRGICO, BOBINAS LISAS, PERMEÁVEIS AO VAPOR E AO AR, IMPERMEÁVEIS A MICRORGANISMOS, RESISTENTES AO CALOR, LIVRES DE NUTRIENTES MICROBIANOS E RESÍDUOS TÓXICOS, TRANSPARÊNCIA DO FILME. DOTADA DE INDICADORES QUÍMICOS QUE MUDAM DE COR APÓS O PROCESSO DE ESTERILIZAÇÃO. TAMANHO 20CMX100M.",
    "CAMPO OPERATÓRIO 45X50 C/50 -PARA USO CIRÚRGICO TIPO CAMPO OPERATÓRIO, 4 CAMADAS, EM TECIDO 100% ALGODÃO, ALTAMENTE ABSORVENTE ISENTA DE IMPUREZAS, COR BRANCA, COM ALÇA DE FIXAÇÃO, REUSÁVEL, MEDINDO APROXIMADAMENTE 45 X 50 CM, ISENTA DE IMPUREZAS E ALVEJANTES, RASGOS E QUALQUER TIPO DE DEFEITO QUE POSSAM AFETAR SEU DESEMPENHO EM USO, ATENDENDO AS NORMAS ABNT- NBR 14.767. APRESENTAR EMBALAGEM EM PACOTES COM 50 PECAS, A EMBALAGEM DEVE CONTER IDENTIFICAÇÃO, LOTE, FABRICAÇÃO, VALIDADE, ISENÇÃO/. VALIDADE MÍNIMA 12 MESES APÓS DATA DA ENTREGA",
    "Material de Ostomia",
    "SERVIÇOS DE SAÚDE OCUPACIONAL",
    "CAMPO FENESTRADO - MEDINDO 45X45 CM; GRAMATURA 30; CONFECCIONADO DE TECIDO NÃO TECIDO POLIPROPILENO; INDICADO PARA PROTEÇÃO E BIOSSEGURANÇA DO PROFISSIONAL DA ÁREA DE SAÚDE E SEU PACIENTE; NÃO ESTÉRIL; EMBALAGEM COM 10 UNIDADES; COM REGISTRO NA ANVISA E CERTIFICADO DE BOAS PRÁTICAS DE FABRICAÇÃO OU CERTIFICADO DE ISENÇÃO.",
    "COMPOSTOS DE PAPEL GRAU CIRÚRGICO MAIS FILME LAMINADO POLIÉSTER/POLIPROPILENO, COM FITA ADESIVA, POSSIBILITANDO ABERTURA ASSÉPTICA, IMPRESSAS COM TINTA INDICATIVA PARA OS PROCESSOS DE ESTERILIZAÇÃO NAS SEGUINTES COMBINAÇÕES: VAPOR SATURADO E ÓXIDO DE ETILENO, EM EMBALAGENS COM 200 UNIDADES NOS TAMANHOS 14CMX29CM; COM REGISTRO NA ANVISA E CERTIFICADO DE BOAS PRÁTICAS DE FABRICAÇÃO OU CERTIFICADO DE ISENÇÃO.",
    "PAPEL GRAU CIRÚRGICO 10 CM. PAPEL COM 70G/ M² COM FILME TRANSPARENTE LAMINADO POLIÉSTER E POLIPROPILENO, SEGURO E RESISTENTE, ISENTO DE RESÍDUOS E IMPUREZAS, COM INDICADORES TERMOQUÍMICOS PARA O PROCESSO DE ESTERILIZAÇÃO A VAPOR E ÓXIDO DE ETILENO. ROLO COM TAMANHO 10CM LARGURA X 100M COMPRIMENTO. REGISTRO NO MINISTÉRIO DA SAÚDE",
    "DETERGENTE ENZIMÁTICO 01 LITROS COM PH NEUTRO E PODER BACTERIOSTÁTICO, ATÓXICO NÃO IRRITANTE PARA A PELE MUCOSAS (COMPROVADO POR LAUDO DE LABORATÓRIOS OFICIAIS OU CREDENCIADOS) NÃO CORROSIVO E BIODEGRADÁVEL, COM NO MÍNIMO 4 ENZIMAS (PROTEASE, AMILASE, CARBOHIDRASE E LIPASE) CONTER SOMENTE TENSOATIVOS NÃO IÔNICO SEM SUA FORMULAÇÃO E ESPECÍFICO PARA REMOÇÃO DE CARGA ORGÂNICA, DISSOLVENDO OS CONTAMINANTES EM ATÉ 5 MINUTOS. EMBALAGEM DE 1 LITRO COM REGISTRO NO MINISTÉRIO DA SAÚDE",
    "FORMOCRESOL DE USO ODONTOLÓGICO, COMPOSIÇÃO COMPATÍVEL COM FORMALDEÍDO, CRESOL, GLICERINA, ÁGUA DESTILADA. EMBALADO EM FRASCO COM 10ML, TRAZENDO EXTERNAMENTE OS DADOS DE IDENTIFICAÇÃO DO PRODUTO,  PROCEDÊNCIA, NÚMERO DE LOTES, DATA DE VALIDADE E NÚMERO DE REGISTRO NO MINISTÉRIO DA SAÚDE; COM REGISTRO NA ANVISA E CERTIFICADO DE BOAS PRÁTICAS DE FABRICAÇÃO OU CERTIFICADO DE ISENÇÃO.",
    "PAPEL GRAU CIRÚRGICO 05 CM. PAPEL COM 70G/ M² COM FILME TRANSPARENTE LAMINADO POLIÉSTER E POLIPROPILENO, SEGURO E RESISTENTE, ISENTO DE RESÍDUOS E IMPUREZAS, COM INDICADORES TERMOQUÍMICOS PARA O PROCESSO DE ESTERILIZAÇÃO A VAPOR E ÓXIDO DE ETILENO. ROLO COM TAMANHO 05CM LARGURA X 100M COMPRIMENTO. REGISTRO NO MINISTÉRIOS DA SAÚDE",
    "HOSPEDAGEM",
    "COLETOR 13 LITROS PARA MATERIAL PERFUROCORTANTE E BIOLÓGICO DESCARTÁVEL DE PAPELÃO. CAPACIDADE ÚTIL MÍNIMA DE 11 LITROS E MÁXIMA DE 13 LITROS. COM TRAVA ESPECIAL DE SEGURANÇA QUE IMPEÇA A VIOLAÇÃO, PAREDES RÍGIDAS, COM CINTA INTERNA DE SEGURANÇA, BANDEJA E SACO PLÁSTICO RESISTENTE A PERFURAÇÕES E VAZAMENTOS. BOCAL DEVE PERMITIR COLOCAÇÃO DO MATERIAL DESCARTADO UTILIZANDO APENAS UMA DAS MÃOS, DE FORMA SEGURA. ALÇAS PARA TRANSPORTE E TAMPA PROTETORA. SUPERFÍCIE EXTERNA DE COR AMARELA E SÍMBOLO PARA MATERIAL INFECTANTE (NBR 7500)",
    "ÁLCOOL ETÍLICO A 96% 1000ML, LÍQUIDO INCOLOR, LÍMPIDO, VOLÁTIL, E DE ODOR CARACTERÍSTICO - FRASCO DE 1000ML. DEVERÁ APRESENTAR REGISTRO DO PRODUTO NO MINISTÉRIO DA SAÚDE E ESTAR DE ACORDO COM O CÓDIGO DE DEFESA DO CONSUMIDOR. O LOTE, A DATA DE FABRICAÇÃO E A DATA DE VALIDADE DEVERÃO VIR IMPRESSO NO RÓTULO. VALIDADE MÍNIMA DE 02 ANOS DA DATA DA ENTREGA; COM REGISTRO NA ANVISA E CERTIFICADO DE BOAS PRÁTICAS DE FABRICAÇÃO OU CERTIFICADO DE ISENÇÃO.",
    "PAPEL GRAU CIRÚRGICO 20 CM. PAPEL COM 70G/ M² COM FILME TRANSPARENTE LAMINADO POLIÉSTER E POLIPROPILENO, SEGURO E RESISTENTE, ISENTO DE RESÍDUOS E IMPUREZAS, COM INDICADORES TERMOQUÍMICOS PARA O PROCESSO DE ESTERILIZAÇÃO A VAPOR E ÓXIDO DE ETILENO. ROLO COM TAMANHO 20CM LARGURA X 100M COMPRIMENTO. REGISTRO NO MINISTÉRIO DA SAÚDE",
    "CAIXA COLETORA PARA MATERIAIS INFECTANTES EPERFUROCORTANTES, COM CAPACIDADE DE 1,5L,CONFECCIONADA EM MATERIAL RESISTENTE. O BOCAL DEVEPERMITIR A COLOCAÇÃO DO RESÍDUO SEM CONTATO DA MÃO COMA CAIXA. O COLETOR DEVE SER DOTADO DE TAMPA PARAFECHAMENTO E ALÇAS QUE PERMITAM SEU MANUSEIO SEGURO.COLORAÇÃO EXTERNA AMARELA, COM LIMITE DE ENCHIMENTO,SÍMBOLO DE MATERIAL INFECTANTE E DEMAIS INSCRIÇÕES EREQUISITOS CONFORME NBR 13853:1997. APRESENTAR REGISTRONO MINISTÉRIO DA SAÚDE/ANVISA. (CIM8484)",
    "ESTETOSCÓPIO PARA AUSCULTA INFANTIL. AUSCULTADOR DUPLO EM ALUMÍNIO COM ALTÍSSIMA SENSIBILIDADE ACÚSTICA, HASTES EM AÇO INOX OU ALUMÍNIO AJUSTÁVEIS QUE PERMITA MELHOR ERGONOMIA, OLIVAS ANATÔMICAS EM SILICONE PARA MELHOR ACÚSTICA E CONFORTO, DIAGRAGMA EM MATERIAL EPOXI/FIBRA DE VIDRO E ANEL ANTI-FRIO PARA CONFORTO TÉRMICO AO PACIENTE. EMBALAGEM INDIVIDUAL, RESISTENTE QUE CONSERVE A INTEGRIDADE DO PRODUTO ATÉ O MOMENTO DO USO, DEVE CONTER OS DADOS DE IDENTIFICAÇÃO E REGISTRO NA ANVISA E NO MINISTÉRIO DA SAÚDE. GARANTIA MÍNIMA DE 2 ANOS",
    "COLETOR PARA MATERIAL PERFUROCORTANTE, LOCAL PARADESCARTE DE AGULHAS, LÂMINAS E OUTROS MATERIAIS CONTAMINADOS PERFURANTES E CORTANTES DESCARTÁVEIS. TOTAL PROTEÇÃO CONTRA PERFURAÇÃO E VAZAMENTO DE FLUIDOS, MAIOR PROTEÇÃO PARA PROFISSIONAIS E PESSOALDE LIMPEZA.  COR EXTERNA: AMARELA, COM DIZERES EM PRETO. CAPACIDADE INTERNA: 13 LITROS. APRESENTAÇÃO: CAIXA DE 10 UNIDADES.",
    "ATADURA ORTOPÉDICA, CONFECCIONADA COM, NO MÍNIMO, 97%ALGODÃO, COM 15CM DE LARGURA E 1,80M DE COMPRIMENTODESENROLADA EM REPOUSO. COM PESO MÍNIMO DE 20,3G PORUNIDADE. ISENTA DE MANCHAS, RASGOS OU FUROS,SOBREPOSIÇÃO DE CAMADAS DE FIBRAS OU EMENDAS, GRUMOSOU APELOTAMENTOS QUE INTERFIRAM EM SUA ESPESSURA.ISENTA DE AMIDO. DEVE PERMITIR ESTIRAMENTO E TRAÇÃO PARAEXECUÇÃO DE TÉCNICAS. ENROLADA SOBRE SI DE FORMA LISA ECOMPACTA. ACONDICIONADA EM PACOTES COM 12 UNIDADES, DEMODO QUE SUA INTEGRIDADE SEJA GARANTIDA, CONTENDONÚMERO DE LOTE, PROCEDÊNCIA, DATA DE FABRICAÇÃO OUESTERILIZAÇÃO E DEMAIS INFORMAÇÕES CONFORME NBR15620:2008. APRESENTAR REGISTRO NO MINISTÉRIO DASAÚDE/ANVISA. (CIM8461)",
    "DETERGENTE LIQUIDO NEUTRO500 ML\r\n<p>Detergente líquido neutro biodegradável, composto por matéria ativa detergente, embalado em frasco plástico flexível de 500ml</p>",
    "TUBO CIRÚRGICO PARA OXIGÊNIO, CONFECCIONADO EM SILICONE 100% PURO, N°: 204 (06 X 12,0 MM), COM NO MÍNIMO 10 METROS SEM INTERRUPÇÕES. EMBALAGEM UNITÁRIA COM REGISTRO NO MINISTÉRIO DA SAÚDE",
    "Material p/reabilitação profissional - Equipamentos e materiais para treinamento e reabilitação profissional.\n",
    "PAPEL GRAU CIRÚRGICO, BOBINAS LISAS, PERMEÁVEIS AO VAPOR E AO AR, IMPERMEÁVEIS A MICRORGANISMOS, RESISTENTES AO CALOR, LIVRES DE NUTRIENTES MICROBIANOS E RESÍDUOS TÓXICOS, TRANSPARÊNCIA DO FILME. DOTADA DE INDICADORES QUÍMICOS QUE MUDAM DE COR APÓS O PROCESSO DE ESTERILIZAÇÃO. TAMANHO 8CMX100M.",
    "COLETOR PARA MATERIAL PERFUROCORTANTE, LOCAL PARADESCARTE DE AGULHAS, LÂMINAS E OUTROS MATERIAIS CONTAMINADOS PERFURANTES E CORTANTES DESCARTÁVEIS. TOTAL PROTEÇÃO CONTRA PERFURAÇÃO E VAZAMENTO DE FLUIDOS, MAIOR PROTEÇÃO PARA PROFISSIONAIS E PESSOALDE LIMPEZA. COR EXTERNA: AMARELA, COM DIZERES EM PRETO. CAPACIDADE INTERNA: 3 LITROS. APRESENTAÇÃO:CAIXA DE 10 UNIDADES.",
    "DETERGENTE MULTIENZIMÁTICO -  CONTENDO 5 ENZIMAS: DUAS PROTEASES, UMA LIPASE, UMA AMILASE E UMA CELULASE; ESTABILIZANTE, CONSERVANTE E ÁGUA, CONTÉM ÁLCOOL ISOPROPÍLICO,  DETERGENTE NÃO IÔNICO, BIODEGRADÁVEL, ATÓXICO, NÃO CORROSIVO, INDICADO PARA LIMPEZA MANUAL OU AUTOMÁTICA. APRESENTAÇÃO: FRASCO DE 1 LITRO. COM NO MÍNIMO 12 MESES DE VALIDADE A PARIR DA DATA DE ENTREGA.",
    "PCA - MATERIAL DE PROTEÇÃO E SEGURANÇA",
    "Material Odontológico",
    "CAMPO OPERATÓRIO SEM FENESTRA, CONFECCIONADO EM TECIDO 100% ALGODÃO OU MISTO DERIVADO DE CELULOSE EM ATÉ 50%, COM QUATRO CAMADAS DE GAZE FIXADAS ENTRE SI, EVITANDO DESLIZAMENTOS. TAMANHO DE 45 X 50CM, COM PESO MÍNIMO DE 25G POR UNIDADE. ALTAMENTE ABSORVENTE, ISENTO DE IMPUREZAS, COR BRANCA, COM ALÇA DE FIXAÇÃO, FIO RADIOPACO E BORDAS DEVIDAMENTE ACABADAS PARA EVITAR DESFIAMENTO. PACOTE COM NO MÍNIMO 50 UNIDADES, CONTENDO DADOS DE IDENTIFICAÇÃO, PROCEDÊNCIA, LOTE, NÚMERO DE CAMADAS E DEMAIS INFORMAÇÕES CONFORME NBR 14767:2009. (CIM8495)",
    "SERVIÇO DE MANUTENÇÃO EM REDE DE ÁGUA",
    "TIRA REAGENTE PARA DETERMINAÇÃO DE GLICEMIA COM PRINCÍPIO DE MEDIÇÃO POR FOTOMETRIA OU AMPEROMETRIA, QUE REALIZE O TESTE EM AMOSTRAS CAPILAR, VENOSA, ARTERIAL E NEONATAL, COM VOLUME MÁXIMO DE AMOSTRA DE 2 MICROLITROS E QUE ACEITE APENAS MG/DL COMO UNIDADE DE MEDIDA. REAÇÃO QUÍMICA MEDIADA PELA ENZIMA GLICOSE DESIDROGENASE, OXIDASE OU SIMILAR COM FAIXA DE MEDIÇÃO ENTRE 10 A 600MG/DL. DEVE PERMITIR A COLETA DE SANGUE COM A TIRA DENTRO OU FORA DO MONITOR, COM TEMPO DE LEITURA DE 5 A 20 SEGUNDOS, DATA E HORA AJUSTÁVEIS E CONDIFICAÇÃO ATRAVÉS DE CHIP CÓDIGO. A EMPRESA DEVERÁ FORNECER O APARELHO EM COMODATO CONFORME A NECESSIDADE DA SECRETARIA DE SAÚDE. O PRODUTO DEVE POSSUIR O CERTIFICADO DE BOAS PRÁTICAS DE FABRICAÇÃO DA ANVISA",
    "PASTILHA SANITARIA",
    "material farmacologico",
    "KIT DE ATENÇÃO BÁSICA COMPOSTO  DOS MANUAIS DIDÁTICOS:  PRESERVATIVO DST, CORPO HUMANO, DOAÇÃO DE SANGUE, SAÚDE BUCAL, VACINAÇÃO, ENDEMIAS, TEATRO TEMÁTICO SUS, CAMPANHAS DE SAÚDE E PIRÂMIDE ALIMENTAR.",
    "DETERGENTE LIQUIDO NEUTRO, 500 ML.\r\n<p class=\"western\" style=\"margin-bottom: 0.35cm; line-height: 115%em; text-align: justify;\"><span style=\"font-family: 'Times New Roman', serif;\"><span style=\"font-size: 10pt;\"><strong>Características mínimas: </strong>Detergente líquido para lavar louça com glicerina, testado dermatologicamente, biodegradável, com registro na ANVISA/ Ministério da Saúde. Embalagem de 500 ml. Validade de no mínimo 90 (noventa) dias a partir da data de entrega do produto.</span></span></p>",
]

def normalize(text: str) -> str:
    if text is None:
        return ""
    s = str(text)
    nfkd = unicodedata.normalize("NFD", s)
    without_accents = "".join(ch for ch in nfkd if unicodedata.category(ch) != "Mn")
    return " ".join(without_accents.casefold().split())

def load_nao_similares(dataset_path: Path = DESCRICOES_SAUDE_PATH) -> list[str]:
    if not dataset_path.exists():
        return []

    dados = json.loads(dataset_path.read_text(encoding="utf-8"))
    similares_norm = {normalize(item) for item in SIMILARES}
    return [item for item in dados if normalize(item) not in similares_norm]

NAO_SIMILARES = load_nao_similares()

def load_cluster(cluster_path: Path) -> list[str]:
    data = json.loads(cluster_path.read_text(encoding="utf-8"))
    # dados_cluster has keys for node ids and possibly 'comunidades' or errors
    descriptions = []
    for k, v in data.items():
        if k in ("comunidades", "comunidades_error"):
            continue
        if isinstance(v, dict):
            descr = v.get("item") or v.get("descricao") or ""
            if descr:
                descriptions.append(descr)
        elif isinstance(v, str):
            descriptions.append(v)
    return descriptions


def load_dataset(dataset_path: Path) -> list[str]:
    return json.loads(dataset_path.read_text(encoding="utf-8"))


def evaluate(cluster_descs: Iterable[str], dataset: Iterable[str]):
    cluster_set = {normalize(d) for d in cluster_descs}

    similares_norm = {normalize(s) for s in SIMILARES}
    nao_sim_norm = {normalize(s) for s in NAO_SIMILARES}

    tp = fp = tn = fn = 0
    labeled = 0
    ignored = 0

    for d in dataset:
        nd = normalize(d)
        if nd in similares_norm:
            label = 1
        elif nd in nao_sim_norm:
            label = 0
        else:
            ignored += 1
            continue

        labeled += 1
        predicted = 1 if nd in cluster_set else 0

        if predicted == 1 and label == 1:
            tp += 1
        elif predicted == 1 and label == 0:
            fp += 1
        elif predicted == 0 and label == 1:
            fn += 1
        elif predicted == 0 and label == 0:
            tn += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else None
    recall = tp / (tp + fn) if (tp + fn) > 0 else None
    f1 = None
    if precision is not None and recall is not None and (precision + recall) > 0:
        f1 = 2 * precision * recall / (precision + recall)
    accuracy = (tp + tn) / labeled if labeled > 0 else None

    return {
        "tp": tp,
        "fp": fp,
        "tn": tn,
        "fn": fn,
        "errados": fp + fn,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "accuracy": accuracy,
        "labeled": labeled,
        "ignored": ignored,
    }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cluster", required=True, help="Caminho para o JSON de cluster")
    p.add_argument("--dataset", required=True, help="Caminho para o JSON com descrições (lista)")
    p.add_argument("--save", required=False, help="Arquivo de saída para métricas (JSON)")
    args = p.parse_args()

    cluster_path = Path(args.cluster)
    dataset_path = Path(args.dataset)

    cluster_descs = load_cluster(cluster_path)
    dataset = load_dataset(dataset_path)

    results = evaluate(cluster_descs, dataset)

    print("Resultados da avaliação:")
    for k, v in results.items():
        print(f"  {k}: {v}")

    if args.save:
        Path(args.save).write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
